telco-core/networking/Network.yaml, telco-core/networking/multinetworkpolicy/multiNetworkPolicyAllowPortProtocol.yaml, telco-core/networking/multinetworkpolicy/multiNetworkPolicyDenyAll.yaml
related jira story: https://issues.redhat.com/browse/CNF-10745
=> CNF-5528: MultinetworkPolicy

telco-core/configuration/reference-crs-kube-compare/optional/logging/ClusterLogSubscription.yaml, telco-core/configuration/reference-crs-kube-compare/required/networking/NMStateSubscription.yaml, telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/metallbSubscription.yaml, telco-core/configuration/reference-crs-kube-compare/required/networking/sriov/SriovSubscription.yaml, telco-core/configuration/reference-crs-kube-compare/required/storage/odf-external/odfSubscription.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogSubscription.yaml, telco-core/configuration/reference-crs/required/networking/NMStateSubscription.yaml, telco-core/configuration/reference-crs/required/networking/metallb/metallbSubscription.yaml, telco-core/configuration/reference-crs/required/networking/sriov/SriovSubscription.yaml, telco-core/configuration/reference-crs/required/storage/odf-external/odfSubscription.yaml
Operators update should be explicitly approved by the administrator
=> Use Manual approve strategy for Install Plans

telco-core/configuration/core-overlay.yaml
Move configuration of _monitoring_, that requires persistent storage, to be done after _ODF_ is configured.
=> Configure ODF

Makefile, telco-hub/configuration/reference-crs/optional/logging/clusterLogging.yaml, telco-hub/configuration/reference-crs/optional/lso/lsoLocalVolumeSet.yaml, telco-hub/configuration/reference-crs/optional/lso/lsoNS.yaml, telco-hub/configuration/reference-crs/optional/lso/lsoOperatorGroup.yaml, telco-hub/configuration/reference-crs/optional/lso/lsoSubscription.yaml, telco-hub/configuration/reference-crs/optional/odf-internal/storageCluster.yaml, telco-hub/configuration/reference-crs/optional/quay/quayNS.yaml, telco-hub/configuration/reference-crs/optional/quay/quayOperatorGroup.yaml, telco-hub/configuration/reference-crs/optional/quay/quaySubscription.yaml, telco-hub/configuration/reference-crs/required/acm/acmAgentServiceConfig.yaml, telco-hub/configuration/reference-crs/required/acm/acmMCH.yaml, telco-hub/configuration/reference-crs/required/acm/acmNS.yaml, telco-hub/configuration/reference-crs/required/acm/acmOperGroup.yaml, telco-hub/configuration/reference-crs/required/acm/acmProvisioning.yaml, telco-hub/configuration/reference-crs/required/acm/acmSubscription.yaml, telco-hub/configuration/reference-crs/required/acm/observabilityMCO.yaml, telco-hub/configuration/reference-crs/required/acm/observatilityNS.yaml, telco-hub/configuration/reference-crs/required/talm/talmSubscription.yaml, telco-hub/install/agent-config.yaml, telco-hub/install/install-config.yaml
Enable yamllint on hub reference CRs. Fix existing errors.
=> Clean up reference CRs

telco-hub/configuration/reference-crs/required/acm/disable-cluster-proxy-addon.json, telco-hub/configuration/reference-crs/required/acm/readme.md
as pointed in the doc
https://docs.openshift.com/container-platform/4.17/edge_computing/ztp-preparing-the-hub-cluster.html#ztp-configuring-hub-cluster-with-argocd_ztp-preparing-the-hub-cluster
=> disable cluster-proxy-addon

telco-hub/configuration/reference-crs/required/acm/observabilityMCO.yaml
Storage calculated based on:
https://github.com/stolostron/capacity-planning/blob/main/calculation/ObsSizingTemplate-Rev1.ipynb
=> ACM MCH obs CR configured with storage

Makefile, telco-core/configuration/Makefile, telco-core/configuration/compare.sh, telco-core/configuration/compare_ignore
This PR includes following changes:
1. Created new make target for comparing references with CRs;
2. Introduced compare.sh script to perform the comparison.
=> Introduced compare script to check the references with CRs

telco-hub/configuration/reference-crs/required/gitops/readme.md
fixed markdown syntax for numberd lists
=> markdown syntax

Dockerfile.telco-core
Added the needed labels to be consumed by the RH image catalog.
=> Updated dockerfile

telco-hub/configuration/reference-crs/optional/odf-internal/odfSubscription.yaml, telco-hub/configuration/reference-crs/optional/quay/quaySubscription.yaml, telco-hub/configuration/reference-crs/required/acm/acmMCH.yaml, telco-hub/configuration/reference-crs/required/acm/acmSubscription.yaml, telco-hub/configuration/reference-crs/required/gitops/gitopsSubscription.yaml
Updating the different subscriptions to the proper version. Not sure if all are now set to the correct version. Need feedback.
=> update subscriptions about hub rds 4.18

Makefile, telco-ran/configuration/Makefile
This PR includes ci checks to telco-ran
=> ztp: CNF-17491: ci checks for telco-ran reference

telco-ran/configuration/kube-compare-reference/ClusterVersionOperator.yaml
=> Bump ran reference version number to 4.19

telco-ran/configuration/kube-compare-reference/ClusterVersionOperator.yaml
=> RAN reference: Fix 4.19 version check template

telco-core/configuration/reference-crs-kube-compare/ReferenceVersionCheck.yaml
=> core reference-template: Bump version check to 4.19

telco-ran/configuration/kube-compare-reference/ClusterVersionOperator.yaml
=> RAN reference: Fix 4.20 version check template

telco-core/configuration/core-upgrade.yaml, telco-core/configuration/reference-crs-kube-compare/compare_ignore, telco-core/configuration/reference-crs/custom-manifests/subscription-validator.yaml
Add logic to core upgrade to ensure ODF subscriptions (auto created by OLM) are AtLatestKnown
=> Update core upgrade

telco-core/configuration/reference-crs-kube-compare/ReferenceVersionCheck.yaml
=> core reference-template: Bump version check to 4.20

telco-core/configuration/reference-crs-kube-compare/metadata.yaml, telco-ran/configuration/kube-compare-reference/metadata.yaml
=> cluster-compare references: Bump metadata references for 4.20

telco-core/configuration/reference-crs-kube-compare/metadata.yaml, telco-ran/configuration/kube-compare-reference/metadata.yaml
=> cluster-compare references: Bump metadata references for 4.19

Makefile, telco-ran/configuration/Makefile, telco-ran/configuration/extra-manifests-builder/Makefile, telco-ran/configuration/kube-compare-reference/Makefile
This MR enables kube-compare-reference ci check for telco-ran directory
=> ztp: CNF-17491: ci validate for telco-ran

telco-hub/configuration/example-overlays-config/gitops/init-argocd-app.yaml, telco-hub/configuration/example-overlays-config/gitops/kustomization.yaml, telco-hub/configuration/reference-crs/required/gitops/argocd-application.yaml
Actually, was never working. But because I changed the reference by mistake, so, the no working of the overlay was hidden.
=> ArgoCD App overlay was not working

telco-core/configuration/reference-crs-kube-compare/metadata.yaml
This pr updates metallb community CR to anyOf (optional)
=> telco-core: OCPBUGS-52157: update metallb community cr to optional

.containerignore, .tekton/telco-core-rds-4-19-pull-request.yaml, .tekton/telco-core-rds-4-19-push.yaml, build/rpms.in.yaml, build/rpms.lock.yaml, telco-core/Dockerfile.telco-core
* Move telco core rds dockerilfe to its desginated dir. 
* Add initial tekton files for build pipelines.
* Add rpm locking for telco core rds container (to be enabled with hermetic builds)
* Add cel expressions to filter pipeline triggers.
=> [release-4.19]: Onboard telco core rds to konflux

.containerignore, .tekton/telco-core-rds-4-18-pull-request.yaml, .tekton/telco-core-rds-4-18-push.yaml, build/rpms.in.yaml, build/rpms.lock.yaml, telco-core/Dockerfile.telco-core
* Add telco core rds dockerfile.
* Add initial tekton files for build pipelines.
* Add rpm locking for telco core rds container (to be enabled with hermetic builds)
* Add cel expressions to filter pipeline triggers.
=> [release-4.18]: Onboard telco core rds to konflux 

.containerignore, .tekton/telco-core-rds-4-17-pull-request.yaml, .tekton/telco-core-rds-4-17-push.yaml, build/rpms.in.yaml, build/rpms.lock.yaml, telco-core/Dockerfile.telco-core
* Add telco core rds dockerfile.
* Add initial tekton files for build pipelines.
* Add rpm locking for telco core rds container (to be enabled with hermetic builds)
* Add cel expressions to filter pipeline triggers.
=> [release-4.17]: Onboard telco core rds to konflux

.containerignore, .tekton/telco-core-rds-4-16-pull-request.yaml, .tekton/telco-core-rds-4-16-push.yaml, build/rpms.in.yaml, build/rpms.lock.yaml, telco-core/Dockerfile.telco-core
* Add telco core rds dockerfile.
* Add initial tekton files for build pipelines.
* Add rpm locking for telco core rds container (to be enabled with hermetic builds)
* Add cel expressions to filter pipeline triggers.
=> [release-4.16]: Onboard telco core rds to konflux

.tekton/OWNERS, OWNERS, OWNERS_ALIASES
This PR updates owners aliases in release-4.19 branch
=> telco-ref: update owners alias 4.19

.tekton/OWNERS, OWNERS, OWNERS_ALIASES
This PR updates OWNERS file in release-4.17
=> telco-ref: update owners alias in 4.17

.tekton/OWNERS, OWNERS, OWNERS_ALIASES
This PR updates owners alias in release-4.16
=> telco-ref: update owners alias in 4.16

.tekton/telco-core-rds-4-16-pull-request.yaml
Corrected the tekton file name.
=> [release-4.16]: fix on cel expression typo

.tekton/telco-core-rds-4-17-pull-request.yaml
Corrected the tekton file name.
=> [release-4.17]: fix on cel expression typo

.tekton/telco-core-rds-4-19-pull-request.yaml, .tekton/telco-core-rds-4-19-push.yaml
This will fix the konflux pipeline which is failing recently.
=> konflux: fixed apply-tags tasks params

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/addr-pool.yaml
=> OCPBUGS-57132: Fix avoidBuggyIPs typo

telco-hub/configuration/reference-crs/required/acm/acmMCE.yaml, telco-hub/configuration/reference-crs/required/acm/kustomization.yaml, telco-hub/configuration/reference-crs/required/gitops/clusterrole.yaml
Enabling the image-base-install-operator. I still need to do some more tests. So, lets keep it as draft.
=> [telco-hub] enable image-based-install-operator

telco-hub/scripts/check_current_versions.sh
by the moment is a very simple script that show
us, the different versions for:
* Subscriptions
* AgentServiceConfig OsImages
* ztp-site-generate patch image
* ImageSetConfiguration for the mirror-registry
=> script to help us know versions of components

.tekton/build-pipeline.yaml
Updates tekton references for conforma violations
=> telco-core: update tekton

telco-ran/configuration/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml, telco-ran/configuration/source-crs/TunedPerformancePatch.yaml
This PR updates the comment in tuned performance patch, such that the user can understand the recommended configuration for stdkernel performance patch and implement it.
=> telco-ran: OCPBUGS-59333: comment update for TunedPerformancePatch

telco-ran/configuration/Makefile, telco-ran/configuration/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml, telco-ran/configuration/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml, telco-ran/configuration/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-hardware-types-configmap.yaml, telco-ran/configuration/argocd/example/policygentemplates/group-du-sno-ranGen.yaml, telco-ran/configuration/argocd/example/policygentemplates/hub-side-templating/configMaps/group-hardware-types-configmap.yaml, telco-ran/configuration/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml, telco-ran/configuration/hack/checkpolicypaths.sh
=> telco-ran: Add CI check for policy consistency

telco-core/configuration/reference-crs-kube-compare/metadata.yaml, telco-core/configuration/reference-crs-kube-compare/optional/other/monitoring-config-cm.yaml, telco-core/configuration/reference-crs/optional/other/monitoring-config-cm.yaml
Updated the observability section in monitoring-config-cm file for Core
=> telco-core: merge acm observability with Core Config

telco-ran/configuration/argocd/example/clusterinstance/example-3node.yaml, telco-ran/configuration/argocd/example/clusterinstance/example-sno.yaml, telco-ran/configuration/argocd/example/clusterinstance/example-standard.yaml, telco-ran/configuration/argocd/example/siteconfig/example-3node.yaml, telco-ran/configuration/argocd/example/siteconfig/example-sno.yaml, telco-ran/configuration/argocd/example/siteconfig/example-standard.yaml
=> telco-ran update all references to 4.20

telco-ran/configuration/kube-compare-reference/functions/must_match_one_of.tmpl, telco-ran/configuration/kube-compare-reference/hack/default_value.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigBoundary.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigBoundaryForEvent.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigDualCardGmWpc.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigForHA.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigForHAForEvent.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigGmWpc.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigMaster.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigMasterForEvent.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigSlave.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigSlaveForEvent.yaml, telco-ran/configuration/kube-compare-reference/ptp-operator/configuration/PtpConfigThreeCardGmWpc.yaml
=> telco-ran: Allow PTP logReduce: enhanced

telco-hub/configuration/reference-crs/required/acm/readme.md
readme update in hub RDS regarding acm observability patch
=> telco-hub: update readme about acm-observability
