openshift-kni/telco-reference

telco-core/configuration/reference-crs/optional/other/monitoring-config-cm.yaml
Since OCP 4.15 setting `DedicatedServiceMonitors` has no effect - https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-monitoring-improved-staleness-handling-for-the-kubelet-service-monitor
=> dedicatedServiceMonitors param removed from monitoring-config-cm.yaml

telco-core/configuration/reference-crs/required/networking/sriov/SriovOperatorConfig.yaml
- Add logLevel to SriovOperatorConfig
Starting from OCP 4.16 GA, the SriovOperatorConfig is no longer automatically created by the Operator upon install. Instead it must be created by cluster administrators.
Option logLevel should be added to SriovOperatorConfig.yaml since it is the default value but more importantly because it is documented as an option users should set when creating the SriovOperatorConfig CR.
- Ensure node draining is on
The option to drain nodes in parallel enables faster rollouts of SR-IOV network configurations. This option is on by default in the code and is explicitly called out in the OpenShift documentation.
https://issues.redhat.com/browse/CNF-7347
https://docs.openshift.com/container-platform/4.16/networking/hardware_networks/configuring-sriov-operator.html
=> SR-IOV: add disableDrain and logLevel parameters to SriovOperatorConfig

telco-core/configuration/reference-crs/optional/other/control-plane-load-kernel-modules.yaml, telco-core/configuration/reference-crs/optional/other/worker-load-kernel-modules.yaml
The xt_u32 kernel module is no longer available, removing from the list
=> Remove unavailable modules

telco-core/configuration/reference-crs/required/networking/metallb/addr-pool.yaml
`metallb.universe.tf/address-pool` annotation is used to request an IP address from the specified address pool when configuring `Service` CR.
=> Drop address-pool from IPAddressPool

telco-core/configuration/reference-crs-kube-compare/metadata.yaml
The
metadata.annotations."operator.sriovnetwork.openshift.io/last-network-namespace" annotation is automatically added and maintained by the SRIOV operator. It should not be included in the comparison.
=> Exclude SRIOV annotation from compare

telco-core/configuration/reference-crs-kube-compare/optional/logging/ClusterLogNS.yaml, telco-core/configuration/reference-crs-kube-compare/required/networking/NMStateNS.yaml, telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/metallbNS.yaml, telco-core/configuration/reference-crs-kube-compare/required/networking/sriov/SriovSubscriptionNS.yaml, telco-core/configuration/reference-crs-kube-compare/required/scheduling/NROPSubscriptionNS.yaml, telco-core/configuration/reference-crs-kube-compare/required/storage/odf-external/odfNS.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogNS.yaml, telco-core/configuration/reference-crs/required/networking/NMStateNS.yaml, telco-core/configuration/reference-crs/required/networking/metallb/metallbNS.yaml, telco-core/configuration/reference-crs/required/networking/sriov/SriovSubscriptionNS.yaml, telco-core/configuration/reference-crs/required/scheduling/NROPSubscriptionNS.yaml, telco-core/configuration/reference-crs/required/storage/odf-external/odfNS.yaml
Workload partitioning can be enabled on multinode cluster but it has not been tested jointly with the annotations. Testing workload partitioning feature with the annotations would be required for that.
=> Delete annotations for workload partitioning

telco-core/configuration/core-baseline.yaml, telco-core/configuration/core-overlay.yaml, telco-core/configuration/reference-crs-kube-compare/optional/logging/ClusterLogServiceAccount.yaml, telco-core/configuration/reference-crs-kube-compare/optional/logging/ClusterLogServiceAccountAuditBinding.yaml, telco-core/configuration/reference-crs-kube-compare/optional/logging/ClusterLogServiceAccountInfrastructureBinding.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogForwarder.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogForwarderDeleted.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogOperatorStatus.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogServiceAccount.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogServiceAccountAuditBinding.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogServiceAccountInfrastructureBinding.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogging.yaml, telco-core/configuration/reference-crs/optional/logging/ClusterLogging5Cleanup.yaml
The upgrade from Cluster Logging Operator 5.x to 6.0 requires a couple steps in the proper order to ensure upgrade without loss of logs. 
1. Set subscription channel to stable-6.0
2. Approve the install plan
3. Wait for the operator/operand to upgrade
4. Create the new API ClusterLogForwarder.observability CR
5. Wait for Valid status
6. Remove old API CRs ClusterLogForwarder.logging and ClusterLogging
This PR builds on #35 by adding support for step 6. Steps 1-5 are included in the previous PR.
=> OCPBUGS-42833: Policy support to upgrade logging 5.x to 6.0

telco-core/configuration/reference-crs/optional/other/sctp_module_mc.yaml
update sctp mc as discussed in previous PR
From prior PR comment:
> The current version of load-sctp-module machineConfig is using different value for ignition version and file permission comparing to Red Hat Official Documentation for Openshift 4.14.
> Updating load-sctp-module machineConfig to align with Red Hat Official Documentation for Openshift 4.14
> [Enabling SCTP on OCP 4.14](https://docs.openshift.com/container-platform/4.14/networking/using-sctp.html#nw-sctp-enabling_using-sctp)
=> update sctp mc

telco-hub/configuration/reference-crs/required/acm/acmMCH.yaml, telco-hub/configuration/reference-crs/required/acm/acmSubscription.yaml, telco-hub/configuration/reference-crs/required/acm/readme.md, telco-hub/configuration/reference-crs/required/gitops/gitopsSubscription.yaml, telco-hub/configuration/reference-crs/required/talm/talmSubscription.yaml
The Hub cluster will not be managed with TALM. Set all operators to Automatic installPlanApproval by default. Customers can control timing of updates by using separate catalogs for new hub cluster versions.
=> Set all approvals to Automatic for Hub operators

Dockerfile.telco-core
A Dockerfile is required here to initiate the migration to Konflux.
=> Added dockerfile for telco-core rds

telco-core/configuration/reference-crs-kube-compare/optional/other/monitoring-config-cm.yaml
_dedicatedServiceMonitors_ part was removed some time ago in b67c2cf5abd9a0a7c17cea982b93ba9e312a1b1e but respective kube-compare CR was missed. Adjusting now.
=> Removed dedicatedServiceMonitors from kube-compare cr

telco-core/configuration/core-overlay.yaml
without setting the policy compliance to "mustonlyhave" we will end up creating the machine config with 4 entries rather than the 2 desired ones when we upgrade from older versions of the reference with that MC in place.
Added mustonlyhave compliance type to the generated policy for sctp mc.
=> Add mustonlyhave compliance type to the generated policy for sctp mc

telco-core/configuration/core-finish.yaml, telco-core/configuration/kustomization.yaml, telco-core/install/custom-manifests/mcp-worker-3.yaml
Adding PolicyGen with unpause and setting maxUnavailable in a unique harmonized example.
Created new MCP worker-3. Update kustomize.
=> add examples of usage with multiple mcps

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/bgp-advr.yaml
=> OCPBUGS-45850: cluster-compare: Allow optional nodeSelectors for BgpAdvertisement CR

telco-hub/configuration/reference-crs/required/acm/observabilityMCO.yaml
Updated storage needs using the capacity planning tool:
https://github.com/stolostron/capacity-planning/blob/main/calculation/ObsSizingTemplate-Rev1.ipynb 
and the requirements for a Telco Hub managing Telco RAN managed clusters.
=> Storage needs based on capacity planning tool

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/bfd-profile.yaml, telco-core/configuration/reference-crs/required/networking/metallb/bfd-profile.yaml
Existing value (_true_) only works if the other side is _FRR_ and not BGP capable router therefore removing it from the reference- and compare- CRs.
=> Loosen validation of echoMode option in BFDProfile

telco-core/configuration/reference-crs-kube-compare/required/networking/Network.yaml, telco-core/configuration/reference-crs/required/networking/Network.yaml
The `reachabilityTotalTimeoutSeconds` parameter in the `Network` CR configures the EgressIP node reachability check total timeout in seconds. The recommended value is `1` second.
=> CNF-13981: set reachabilityTotalTimeoutSeconds=1

telco-core/configuration/core-finish.yaml, telco-core/configuration/core-upgrade.yaml, telco-core/configuration/reference-crs-kube-compare/compare_ignore, telco-core/configuration/reference-crs/custom-manifests/README.md, telco-core/configuration/reference-crs/custom-manifests/mcp-worker-1.yaml, telco-core/configuration/reference-crs/custom-manifests/mcp-worker-2.yaml, telco-core/configuration/reference-crs/custom-manifests/mcp-worker-3.yaml
For generation of policies all path references must exist under the top level kustomize directory (configuration in this case). Update the paths and make "local" copies of MCP CRs. Add a README to explain the content and use of MCP.
=> Update the MCP reference to fix paths

OWNERS
With the addition of the telco-ran reference we need reviewers/approvers for that use case included in the OWNERS file.
=> Update OWNERS to support RAN reference

telco-core/configuration/reference-crs-kube-compare/metadata.yaml, telco-core/configuration/reference-crs-kube-compare/required/performance/PerformanceProfile.yaml, telco-core/configuration/reference-crs-kube-compare/unordered_list.tmpl, telco-core/configuration/reference-crs/required/performance/PerformanceProfile.yaml
The irdma kernel module can cause an excessive number of interrupts on CPUs with large numbers of cores. This removes the module. CNF-16652
=> Exclude the irdma kernel module

telco-core/configuration/reference-crs-kube-compare/required/networking/sriov/sriovNetworkNodePolicy.yaml
Without proper defaults, running "make check" will fail in upcoming
cluster-compare releases.
=> OCPBUGS-54880: core cluster-compare: default empty struct values

telco-ran/configuration/argocd/example/acmpgfrompgt/hub-side-templating/source-crs/ClusterLogSubscription.yaml, telco-ran/configuration/argocd/example/acmpgfrompgt/out/ztp-common_policy.open-cluster-management.io_v1_policy_common-latest-subscriptions-policy.yaml, telco-ran/configuration/argocd/example/acmpgfrompgt/source-crs/ClusterLogSubscription.yaml, telco-ran/configuration/kube-compare-reference/required/cluster-logging/ClusterLogSubscription.yaml, telco-ran/configuration/source-crs/ClusterLogSubscription.yaml
Changed and updated the subscription CR and references for ClusterLoggingOperator operator to use stable-6.2 channel instead of stable-6.1. The reason being, stable-6.1 is removed from 4.19 catalog.
=> OCPBUGS-54718: set CLO subscription channel to 6.2

telco-hub/configuration/reference-crs/required/gitops/ztp-installation/app-project.yaml
The provisioning ZTP Argo App is missing the following **image-based** resources to be managed: `ImageClusterInstall` and `DataImage`
cc/  @imiller0
=> Adds image-based cluster installation CRDs to be managed by Argo ZTP app

telco-core/configuration/reference-crs-kube-compare/required/networking/sriov/sriovNetworkNodePolicy.yaml
Without proper defaults, running "make check" will fail in upcoming
cluster-compare releases.
=> OCPBUGS-54973: core cluster-compare: default empty struct values

telco-core/configuration/reference-crs-kube-compare/required/networking/sriov/sriovNetworkNodePolicy.yaml
Without proper defaults, running "make check" will fail in upcoming
cluster-compare releases.
=> OCPBUGS-54974: core cluster-compare: default empty struct values

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/addr-pool.yaml, telco-core/configuration/reference-crs/required/networking/metallb/addr-pool.yaml
Leave IP address assignment to the operators
=> Loosen requirement for  static assignment with IPAddressPool

telco-ran/configuration/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml, telco-ran/configuration/argocd/example/policygentemplates/common-ranGen.yaml
This MR replaces references to DisconnectedICSP with DisconnectedIDMS in argoCD examples.
=> ztp: update disconnected-idms in acm examples

telco-ran/configuration/kube-compare-reference/metadata.yaml, telco-ran/configuration/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml, telco-ran/configuration/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml, telco-ran/configuration/kube-compare-reference/unordered_list.tmpl
- **RAN reference: Cleanup PerformanceProfile template**
- **RAN reference: Allow setting cpufreq governor when perPodPowermanagement is set**
- **RAN reference: Optionally allow max_perf_pct sysfs in Tuned**
=> OCPBUGS-54201: Allow RAN reference PowerSave mode variations in node tuning objcets

telco-core/configuration/reference-crs-kube-compare/required/networking/NMState.yaml
=> OCPBUGS-56367: core cluster-compare: Repair NMState template when spec is not empty

telco-core/configuration/reference-crs-kube-compare/metadata.yaml
=> OCPBUGS-48492: core RDS: Ignore k8s.v1.cni.cncf.io/resourceName annotation

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/addr-pool.yaml
=> OCPBUGS-48672: core RDS: Allow 'avoidBuggyIps' in metallb IpAddressPools

telco-ran/configuration/kube-compare-reference/metadata.yaml
=> OCPBUGS-54716: RAN reference: Ignore new security.openshift.io/MinimallySufficientPodSecurityStandard annotation

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/addr-pool.yaml
=> OCPBUGS-56873: core RDS: Allow 'avoidBuggyIps' in metallb IpAddressPools

telco-ran/configuration/kube-compare-reference/default_value.yaml, telco-ran/configuration/source-crs/PtpConfigDualFollower.yaml
Change the default value from 65 seconds to 5 seconds
=> Fix default holdover value for 2 port Ordinary clock

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/addr-pool.yaml
=> OCPBUGS-48672: Fix avoidBuggyIPs typo

telco-hub/configuration/example-overlays-config/acm/acmMirrorRegistryCM-patch.yaml, telco-hub/configuration/example-overlays-config/acm/kustomization.yaml
This PR adds an overlay configuration for ACM mirror registry ConfigMap, allowing users to easily configure their mirror registry settings without modifying the base configuration files.
The overlay includes:
- acmMirrorRegistryCM-patch.yaml - A patch file for customizing the ACM mirror registry configuration
- Updated kustomization.yaml to include the new patch
=> telco-hub: add overlay for ACM mirror registry config

telco-ran/configuration/kube-compare-reference/Makefile
This PR update helm binary version to 3.18.4 for fixing CVE-2025-53547
=> ztp: OCPBUGS-59092: update helm to 3.18.4 in kube-compare-reference [release-4.19]

telco-hub/configuration/example-overlays-config/logging/README.md, telco-hub/configuration/example-overlays-config/logging/cluster-log-forwarder-patch.yaml, telco-hub/configuration/example-overlays-config/logging/kustomization.yaml, telco-hub/configuration/reference-crs/optional/logging/clusterLogForwarder.yaml, telco-hub/configuration/reference-crs/optional/logging/clusterLogServiceAccount.yaml, telco-hub/configuration/reference-crs/optional/logging/clusterLogServiceAccountAuditBinding.yaml, telco-hub/configuration/reference-crs/optional/logging/clusterLogServiceAccountInfrastructureBinding.yaml, telco-hub/configuration/reference-crs/optional/logging/kustomization.yaml
Implements ClusterLogForwarder configuration for telco-hub overlays to enable centralized log forwarding to Kafka with hub-specific labeling. Fixes [CNF-18888](https://issues.redhat.com/browse/CNF-18888).
- **ClusterLogForwarder resource**: Added to `telco-hub/configuration/reference-crs/optional/logging/`
- **Example overlays**: Created `example-overlays-config/logging/` with kustomize patches
- **Pattern integration**: Updated `values-hub.yaml` with logging component patches
- **Documentation**: Added comprehensive comments and configuration examples
- ✅ Forwards audit and infrastructure logs to Kafka
- ✅ Hub-specific metadata labels for log identification
- ✅ ArgoCD-compatible with proper sync annotations
- ✅ Environment-specific customization via kustomize patches
- ✅ Example …
=> CNF-18888: telco-hub: add ClusterLogForwarder for centralized logging

telco-hub/configuration/reference-crs/required/acm/acmMCH.yaml, telco-hub/configuration/reference-crs/required/acm/pull-secret-copy.yaml
- Remove ManagedClusterSetBinding 'global' from openshift-storage namespace, which was incorrectly placed outside the ACM namespace scope.
- Update ManagedClusterSetBinding in observability to use 'default' clusterSet instead of 'global' for consistency.
Signed-off-by: Leonardo Ochoa-Aday <lochoa@redhat.com>
=> CNF-18869: ACM: correct MultiClusterHub namespace to open-cluster-management

telco-core/configuration/reference-crs-kube-compare/required/scheduling/NROPSubscription.yaml, telco-core/configuration/reference-crs/required/scheduling/NROPSubscription.yaml
This PR adds installPlanApproval to NROPSubscription CR, which was previously causing deviation in cluster-compare tool
=> telco-core: OCPBUGS-60170: installPlanApproval in NROPSubscription

telco-hub/configuration/reference-crs/optional/backup-recovery/dataProtectionApplication.yaml
Fixes a validation error in the telco-hub OADP DataProtectionApplication manifest by adding the missing `apiVersion` field.
The `DataProtectionApplication` CR in `telco-hub/configuration/reference-crs/optional/backup-recovery/dataProtectionApplication.yaml` was missing the required `apiVersion` field, causing:
- Kubernetes validation failures during apply
- Argo CD sync errors
- Inability to create the DPA resource
Added `apiVersion: oadp.openshift.io/v1alpha1` to align with the OADP CRD version used elsewhere in the repository (specifically matching `telco-ran/configuration/source-crs/OadpDataProtectionApplication.yaml`).
- **Modified:** `telco-hub/configuration/reference-crs/optional/backup-recovery/dataProtectionApplication.yaml`
- Added `apiVersion: oadp.openshift.io/v1alpha1` after …
=> OCPBUGS-60446: fix(oadp): [telco-hub] add apiVersion to DataProtectionApplication manifest

telco-ran/configuration/kube-compare-reference/default_value.yaml, telco-ran/configuration/kube-compare-reference/metadata.yaml, telco-ran/configuration/kube-compare-reference/required/cluster-tuning/monitoring-configuration/ReduceMonitoringFootprint.yaml, telco-ran/configuration/source-crs/ReduceMonitoringFootprint.yaml
Updated the observability part on the Reduce monitoring footprint file in response to [CNF-13398](https://issues.redhat.com/browse/CNF-13398)
Includes update to kube-compare reference with inline capture group for parsing fromSecret and fromClusterClaim values
cc: @sabbir-47 @imiller0
=> CNF-13398: merge ACM observability with RAN config

telco-core/configuration/reference-crs-kube-compare/optional/networking/networkAttachmentDefinition.yaml, telco-core/configuration/reference-crs/optional/networking/networkAttachmentDefinition.yaml
`nodeSelector` isn't a valid option for CR and causes issues like:
```bash
`NetworkAttachmentDefinition in version "v1" cannot be handled as a NetworkAttachmentDefinition:
strict decoding error: unknown field "spec.nodeSelector"`
```
=> Drop nodeSelector from NetworkAttachmentDefinition CR

telco-hub/configuration/reference-crs/required/gitops/kustomization.yaml
I dont know when we missed this. But, looks that the kustomization is missing some manifests to configure the Policies correctly.
=> added missing yamls to gitops kustomization

telco-core/configuration/reference-crs/optional/other/monitoring-config-cm.yaml
This PR wraps the fromSecret lookup for ACM observability so that it does not fail when it is disabled (and hub-info-secret is not present) for core
=> telco-core: skip secret lookup if acm observability is disabled

telco-core/configuration/reference-crs-kube-compare/required/networking/metallb/bgp-peer.yaml, telco-core/configuration/reference-crs/required/networking/metallb/bgp-peer.yaml
Added accepted defaults for bgppeer in kube-compare-reference
=> telco-core: OCPBUGS-59296: add defaults for bgppeer

telco-core/configuration/reference-crs-kube-compare/required/scheduling/nrop.yaml
This PR allows cluster compare tool to accept logLevel field in nrop (if its present) and not show a diff
=> telco-core: OCPBUGS-59293: cluster compare to accept logLevel field in nrop

telco-core/configuration/Makefile, telco-core/configuration/hack/cluster-default-crs/README, telco-core/configuration/hack/cluster-default-crs/node.config.yaml, telco-core/configuration/reference-crs-kube-compare/compare_ignore, telco-core/configuration/reference-crs-kube-compare/metadata.yaml, telco-core/configuration/reference-crs-kube-compare/required/machine-config/cgroup-check.yaml, telco-core/configuration/reference-crs-kube-compare/required/machine-config/container-runtime.yaml
All workloads should be moving to cgroup v2. Add a required check for cgroup. If users remain on cgroup v1 the check serves as a reminder that workloads must be moved to v2.
Manual backport of https://github.com/openshift-kni/telco-reference/pull/269
=> OCPBUGS-62709: telco-core: Add cgroup and runtime checks
